apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: echo-kind-worker
  labels:
    run: echo
spec:
  containers:
  - image: inanimate/echo-server
    imagePullPolicy: Always
    name: echo
    ports:
    - containerPort: 8080
      hostPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  nodeName: kind-worker
  priority: 0
